---
execute:
  cache: false
  eval: true
  echo: true
  warning: false
---

# The spotriver GUI

## Hyperparameter Tuning

Calls `run_spot_river_experiment` from 
`spotRiver.tuner.run.py` with the following parameters:

* MAX_TIME,
* INIT_SIZE
* PREFIX
* horizon
* n_total
* perc_train
* oml_grace_period
* data_set
* prepmodel
* coremodel

### The run_spot_river_experiment Method

`run_spot_river_experiment` calls the tuner spot after processing the following steps:

1. Generate an experiment name.
2. Initialize the `fun_control` dictionary.
3. Select the data set based on the `data_set` parameter and generate a data frame.
4. Splits the data into training and test sets.
5. Sets the oml_grace_period parameter.
6. Select the preprocessing model based on the `prepmodel` parameter.
7. Sets the weights for the evaluation function and the weight coeffient.
8. Loads the coremodel based on the `coremodel` parameter with hyperparameters set to the values specified in the `RiverHyperDict` dictionary.
9. Determines the default hyperparameters.
10. Selects the evaluation function: `HyperRiver.fun_oml_horizon`.
11. Determines hyperparameter types, names, lower and upper bounds for the `spot` tuner.
12. Starts tensorboard as a background process.
13. Starts the `spot` tuner.

When the tuner is finished, the following steps are performed:

1. The tensorboard process is terminated.
2. The spot_tuner object and the `fun_control` dictionary are returned.

After the tuner is finished, the following information is available:




### Binary Classification




## Analysis