project:
  type: book
  output-dir: docs

book:
  title: "Hyperparameter Tuning Cookbook"
  subtitle: "A guide for scikit-learn, PyTorch, river, and spotPython"
  author:
  - name: Thomas Bartz-Beielstein
    affiliations:
      - name: SpotSeven Lab
      - city: Gummersbach
        country: Germany
        postal-code: 51643
    orcid: 0000-0002-5938-5158
    email: bartzbeielstein@gmail.com
    url: 'https://www.spotseven.de'
  date: last-modified
  date-format: "MMM D, YYYY"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/sequential-parameter-optimization/spotPython
  downloads: [pdf]
  sharing: [twitter, linkedin]
  twitter-card: true
  cover-image: cover.png
  cover-image-alt: |
    Sequential Parameter Optimization Toolbox (SPOT) for Python (Logo)
  chapters:
    - index.qmd
    - part: "Optimization"
      chapters:
      - 001_optimization_surrogate.qmd
      - 002_awwe.qmd
      - 003_scipy_optimize_intro.qmd
      - 004_spot_sklearn_optimization.qmd
    - part: "Numerical Methods"
      chapters:
      - 005_num_rsm.qmd
      - 006_num_gp.qmd
      - 007_num_spot_intro.qmd
      - 008_num_spot_multidim.qmd
      - 009_num_spot_anisotropic.qmd
      - 010_num_spot_sklearn_surrogate.qmd
      - 011_num_spot_sklearn_gaussian.qmd
      - 012_num_spot_ei.qmd
      - 013_num_spot_noisy.qmd
      - 014_num_spot_ocba.qmd
    # - part: "Introduction to Hyperparameter Tuning"
    #   chapters:
    #   - 015_hpt.qmd
    # - part: "Hyperparameter Tuning with Sklearn"
    #   chapters:
    #   - 016_spot_hpt_sklearn.qmd
    #   - 017_spot_hpt_sklearn_classification.qmd
    #   - 018_spot_hpt_sklearn_multiclass_classification_randomforest.qmd
    #   - 019_spot_hpt_sklearn_multiclass_classification_xgb.qmd
    #   - 020_spot_hpt_sklearn_multiclass_classification_svc.qmd
    #   - 021_spot_hpt_sklearn_multiclass_classification_knn.qmd
    # - part: "Hyperparameter Tuning with River"
    #   chapters:
    #   - 022_spot_hpt_river.qmd
    #   - 023_spot_river_gui.qmd
    #   - 024_spot_hpt_river_friedman_hatr.qmd
    #   - 025_spot_hpt_river_friedman_amfr.qmd
    #   - 026_spot_hpt_river_bananas_amfc.qmd
    - part: "Hyperparameter Tuning with PyTorch Lightning"
      chapters:
      - 031_spot_lightning_linear_diabetes.qmd
      - 032_spot_lightning_rnn_diabetes.qmd
  appendices:
    - a_01_intro_to_notebooks.qmd
    - a_02_git_intro_en.qmd
    - a_03_python_intro_en.qmd
    - a_04_spot_doc.qmd
    - references.qmd

bibliography: bart23i.bib
execute:
  cache: false
  eval: false
  echo: true
  warning: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    keep-tex: true



