project:
  type: book
  output-dir: docs

book:
  title: "Hyperparameter Tuning Cookbook"
  subtitle: "A guide for scikit-learn, PyTorch, river, and spotPython"
  author:
  - name: Thomas Bartz-Beielstein
    affiliations:
      - name: SpotSeven Lab
      - city: Gummersbach
        country: Germany
        postal-code: 51643
    orcid: 0000-0002-5938-5158
    email: bartzbeielstein@gmail.com
    url: 'https://www.spotseven.de'
  date: last-modified
  date-format: "MMM D, YYYY"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/sequential-parameter-optimization/spotPython
  downloads: [pdf]
  sharing: [twitter, linkedin]
  twitter-card: true
  cover-image: cover.png
  cover-image-alt: |
    Sequential Parameter Optimization Toolbox (SPOT) for Python (Logo)
  chapters:
    - index.qmd
    - part: "Optimization"
      chapters:
      - 00000_optimization_surrogate.qmd
      - 002_awwe.qmd
      - 004_scipy_optimize_intro.qmd
      - 05_spot_sklearn_optimization.qmd
    - part: "Numerical Methods"
      chapters:
      - 001_optimization_rsm.qmd
      - 003_optimization_gp.qmd
      - 01_spot_intro.qmd
      - 02_spot_multidim.qmd
      - 03_spot_anisotropic.qmd
      - 04_spot_sklearn_surrogate.qmd
      - 06_spot_sklearn_gaussian.qmd
      - 07_spot_ei.qmd
      - 08_spot_noisy.qmd
      - 09_spot_ocba.qmd
    - part: "Introduction to Hyperparameter Tuning"
      chapters:
      - 111_hpt.qmd
    - part: "Hyperparameter Tuning with Sklearn"
      chapters:
      - 100_spot_hpt_sklearn.qmd
      - 10_spot_hpt_sklearn_classification.qmd
      - 16_spot_hpt_sklearn_multiclass_classification_randomforest.qmd
      - 17_spot_hpt_sklearn_multiclass_classification_xgb.qmd
      - 18_spot_hpt_sklearn_multiclass_classification_svc.qmd
      - 19_spot_hpt_sklearn_multiclass_classification_knn.qmd
    - part: "Hyperparameter Tuning with River"
      chapters:
      - 200_spot_hpt_river.qmd
      - 0000spot_river_gui.qmd
      - 13_spot_hpt_river_friedman_hatr.qmd
      - 51_spot_hpt_river_friedman_amfr.qmd
      - 52_spot_hpt_river_bananas_amfc.qmd
    - part: "Hyperparameter Tuning with PyTorch"
      chapters:
      - 300_spot_hpt_pytorch.qmd
      - 14_spot_ray_hpt_torch_cifar10.qmd
      - 31_spot_lightning_csv.qmd      
  appendices:
    - 91_intro_to_notebooks.qmd
    - 9999_git_intro_en.qmd
    - 911_python_intro_en.qmd
    - 99_spot_doc.qmd
    - references.qmd

bibliography: bart23i.bib
execute:
  cache: false
  eval: false
  echo: true
  warning: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    keep-tex: true



