project:
  type: book
  output-dir: docs

book:
  title: "Hyperparameter Tuning Cookbook"
  subtitle: "A guide for scikit-learn, PyTorch, river, and spotpython"
  author:
  - name: Thomas Bartz-Beielstein
    affiliations:
      - name: SpotSeven Lab
      - city: Gummersbach
        country: Germany
        postal-code: 51643
    orcid: 0000-0002-5938-5158
    email: bartzbeielstein@gmail.com
    url: 'https://www.spotseven.de'
  date: last-modified
  date-format: "MMM D, YYYY"
  sidebar:
    style: docked
    background: light
  search: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2024, T. Bartz-Beielstein" 
    right: 
      - icon: github
        href: https://sequential-parameter-optimization.github.io/Hyperparameter-Tuning-Cookbook/
      - icon: twitter 
        href: https://x.com/bartzbeielstein   
  repo-url: https://github.com/sequential-parameter-optimization/spotpython
  downloads: [pdf]
  sharing: [twitter, linkedin]
  twitter-card: true
  cover-image: cover.png
  cover-image-alt: |
    Sequential Parameter Optimization Toolbox (SPOT) for Python (Logo)
  keyword: "hyperparameter tuning, artificial intelligence, machine learning, streaming data, online algorithms"
  chapters:
    - index.qmd
    - part: "Optimization"
      chapters:
      - 001_optimization_surrogate.qmd
      - 002_awwe.qmd
      - 003_scipy_optimize_intro.qmd
      - 004_spot_sklearn_optimization.qmd
    - part: "Numerical Methods"
      chapters:
      - 005_num_rsm.qmd
      - 006_num_gp.qmd
      - 007_num_spot_intro.qmd
      - 008_num_spot_multidim.qmd
      - 009_num_spot_anisotropic.qmd
      - 010_num_spot_sklearn_surrogate.qmd
      - 011_num_spot_sklearn_gaussian.qmd
      - 012_num_spot_ei.qmd
      - 013_num_spot_noisy.qmd
      - 014_num_spot_ocba.qmd
      - 015_num_spot_correlation_p.qmd
      - 016_num_spot_factorial.qmd
      - 017_num_spot_user_function.qmd
    - part: "Data-Driven Modeling and Optimization"
      chapters:
      - 100_ddmo.qmd
    - part: "Machine Learning and AI"
      chapters:
      - 200_mlai.qmd
    - part: "Introduction to Hyperparameter Tuning"
      chapters:
      - 300_hpt_intro.qmd
    - part: "Hyperparameter Tuning with Sklearn"
      chapters:
       - 400_spot_hpt_sklearn.qmd
       - 401_spot_hpt_sklearn_classification.qmd
    #   - 018_spot_hpt_sklearn_multiclass_classification_randomforest.qmd
    #   - 019_spot_hpt_sklearn_multiclass_classification_xgb.qmd
    #   - 020_spot_hpt_sklearn_multiclass_classification_svc.qmd
    #   - 021_spot_hpt_sklearn_multiclass_classification_knn.qmd
    - part: "Hyperparameter Tuning with River"
      chapters:
       - 500_spot_hpt_river.qmd
       - 501_spot_river_gui.qmd
       - 502_spot_hpt_river_friedman_htr.qmd
       - 503_spot_hpt_river_friedman_amfr.qmd
    #   - 026_spot_hpt_river_bananas_amfc.qmd
    #   - 027_spot_hpt_river_trump_rules.qmd
    - part: "Hyperparameter Tuning with PyTorch Lightning"
      chapters:
      - 700_lightning_basic.qmd
      - 701_lightning_details.qmd
      - 702_lightning_user_datamodule.qmd
      - 600_spot_lightning_data.qmd
      - 601_spot_hpt_light_diabetes.qmd
      - 601_spot_hpt_light_user_data.qmd
      - 601_spot_hpt_light_user_model.qmd
      - 601_spot_hpt_light_pinn.qmd
      #- 031_spot_lightning_linear_diabetes.qmd
      # - 032_spot_lightning_rnn_diabetes.qmd
      # - 033_spot_lightning_linear_sensitive.qmd
      - 602_spot_lightning_xai.qmd
      - 603_spot_lightning_transformer_introduction.qmd
      - 603_spot_lightning_transformer_hpt.qmd
      # - 036_spot_lightning_transformer_diabetes.qmd
      - 604_spot_lightning_save_load_models.qmd
      - 605_spot_hpt_light_diabetes_resnet.qmd
      - 606_spot_hpt_light_diabetes_user_resnet.qmd
      # - 607_spot_hpt_light_multinet.qmd
      - 608_spot_hpt_light_condnet.qmd
  appendices:
    - a_01_intro_to_notebooks.qmd
    - a_02_git_intro_en.qmd
    - a_03_python_intro_en.qmd
    - a_04_spot_doc.qmd
    - a_05_datasets.qmd
    - a_06_slurm.qmd
    - a_07_package.qmd
    - a_99_solutions.qmd
    - references.qmd

bibliography: bart23i.bib
google-scholar: true
citation:
  type: article-journal
  container-title: "arXiv"
  doi: "10.48550/arXiv.2307.10262"
  url: https://arxiv.org/abs/2307.10262
execute:
  cache: false
  eval: false
  echo: true
  warning: false
  keep-ipynb: true

format:
  html:
    theme: cosmo
    code-fold: false
  pdf:
    documentclass: scrbook
    fontsize: 10pt
    papersize: a4paper
    keep-tex: true
    code-fold: true
    include-in-header:
      text: |
        \usepackage{mdframed}
        \usepackage{pseudo}
        \usepackage{makeidx}
        \usepackage{glossaries}
        \makeglossaries
        \newacronym{adwin}{ADWIN}{Adaptive Windowing}
        \newacronym{alma}{ALMA}{Approximative Large-Margin-Algorithmus}
        \newacronym{bip}{BIP}{Bruttoinlandsprodukt}
        \newacronym{bml}{BML}{Batch Machine Learning}
        \newacronym{bo}{BO}{Bayesian Optimization}
        \newacronym{cart}{CART}{Classification And Regression Tree}
        \newacronym{cv}{CV}{Cross Validation}
        \newacronym{cvfdt}{CVFDT}{Concept-adapting Very Fast Decision Tree}
        \newacronym{dace}{DACE}{Design and Analysis of Computer Experiments}
        \newacronym{ddm}{DDM}{Drift Detection Method}
        \newacronym{dl}{DL}{Deep Learning}
        \newacronym{doe}{DOE}{Design of Experiments}
        \newacronym{efdt}{EFDT}{Extremely Fast Decision Tree}
        \newacronym{gbrt}{gbrt}{Gradient Boosting Regression Tree}
        \newacronym{gcd}{GCD}{Greatest Common Divisor}
        \newacronym{gra}{GRA}{Global Recurring Abrupt}
        \newacronym{hat}{HAT}{Hoeffding Adaptive Tree}
        \newacronym{hatc}{HATC}{Hoeffding Adaptive Tree Classifier}
        \newacronym{hatr}{HATR}{Hoeffding Adaptive Tree Regressor}
        \newacronym{hpt}{HPT}{Hyperparameter Tuning}
        \newacronym{ht}{HT}{Hoeffding Tree}
        \newacronym{htc}{HTC}{Hoeffding Tree Classifier}
        \newacronym{htr}{HTR}{Hoeffding Tree Regressor}
        \newacronym{ki}{KI}{Künstliche Intelligenz}
        \newacronym{kpi}{KPI}{Key Performance Indicator}
        \newacronym{mae}{MAE}{Mean Absolute Error}
        \newacronym{ml}{ML}{Machine Learning}
        \newacronym{moa}{MOA}{Massive Online Analysis}
        \newacronym{mse}{MSE}{Mean Squared Error}
        \newacronym{oml}{OML}{Online Machine Learning}
        \newacronym{pa}{PA}{Passive-Aggressive}
        \newacronym{pca}{PCA}{Principal Component Analysis}
        \newacronym{rf}{RF}{Random Forest}
        \newacronym{river}{river}{River: Online machine learning in Python}
        \newacronym{rmoa}{RMOA}{Massive Online Analysis in R}
        \newacronym{rocauc}{ROC AUC}{AUC (Area Under The Curve) ROC (Receiver Operating Characteristics)}
        \newacronym{sea}{SEA}{SEA synthetic dataset}
        \newacronym{sklearn}{sklearn}{scikit-learn: Machine Learning in Python}
        \newacronym{smbo}{SMBO}{Surrogate Model Based Optimization}
        \newacronym{smote}{SMOTE}{Synthetic Minority Oversampling Technique}
        \newacronym{spo}{SPO}{Sequential Parameter Optimization}
        \newacronym{spot}{SPOT}{Sequential Parameter Optimization Toolbox}
        \newacronym{spotpython}{spotPython}{Sequential Parameter Optimization Toolbox for Python}
        \newacronym{spotriver}{spotRiver}{Sequential Parameter Optimization Toolbox for River}
        \newacronym{sgd}{SGD}{Stochastic Gradient Descent}
        \newacronym{svm}{SVM}{Support Vector Machine}
        \newacronym{vfdt}{VFDT}{Very Fast Decision Tree}
        \makeindex
    include-after-body:
      text: |
        \printglossary
        \printindex



