# Data-Driven Modeling and Optimization




* [Histograms, Clearly Explained](https://youtu.be/qBigTkBLU6g)
* [The Main Ideas behind Probability Distributions](https://youtu.be/oI3hZJqXJuc)
* [The Normal Distribution, Clearly Explained!!!](https://youtu.be/rzFX5NWojp0)
* [The mean, the media, and the mode]
* [The exponential distribution]
* [Population and Estimated Parameters, Clearly Explained!!!](https://youtu.be/vikkiwjQqfU)
* [Calculating the Mean, Variance and Standard Deviation, Clearly Explained!!!](https://youtu.be/SzZ6GpcfoQY)
* [What is a mathematical model?]
* [Sampling from a Distribution, Clearly Explained!!!](https://youtu.be/XLCWeSVzHUU)
* [Hypothesis Testing and the Null-Hypothesis, Clearly Explained!!!]
* [Alternative Hypotheses, Main Ideas]
* [p-values: What they are and how to interpret them]
* [How to calculate p-values]
* [p-hacking: What it is and how to avoid it]
* [Covariance, Clearly Explained!!!]
* [Pearson's Correlation, Clearly Explained]
* [Boxplots are Awesome]
* [R-squared, Clearly Explained](https://youtu.be/2AQKmw14mHM)
  * Note: When I first made this video, I was thinking about how R-squared relates to Linear Regression, which will not fit a line worse than the mean of the y-axis values. This is because if the values along the x-axis are truly useless in terms of predicting y-axis values, then the slope of the line used to make predictions will be 0, and the intercept will equal the mean. However, it is possible to simply draw a line that fits the data worse than the mean and get a negative R^2. 
* [The main ideas of fitting a line to data (The main ideas of least squares and linear regression.)](https://www.youtube.com/embed/PaFPbb66DxQ)
* [Linear Regression, Clearly Explained](https://youtu.be/nk2CQITm_eo)
* [Multiple Regression, Clearly Explained]